### PR TITLE
Various fixes.

### PR DESCRIPTION
**Pull request by ghost**
* Fixed required fields error when already logged in.
* Fixed some notices.
* Fixed issues with PayPal Express.
* Fixed bug where subscribe label output "1".

### CODE REVIEW

**Comment by seb86** [comment]
Hi @strangerstudios. It seems there is a small conflict in one of the files. According to your fork you are 3 commits behind the master branch. That might be it.

**Comment by strangerstudios** [comment]
I fixed the merge issues. The pull request has been updated. FYI, the issue was around these lines here:
https://github.com/seb86/MailPoet-Paid-Memberships-Pro-Add-on/blob/master/includes/mailpoet-paid-memberships-pro-addon-functions.php#L45-L50

Just two different ways of fixing a bug there. I think I went with yours.

**Comment by strangerstudios** [comment]
Oops. Nevermind. Used mine. It was slightly different. If a user is logged in, the bemail field is not required. If you're using a gateway like Stripe or PayPal Express, the billing address fields are optional and so bemail might not be set. All users should have an email in WP which should be used.

This whole function to set required fields might be redundant since these fields are required by PMPro by default anyway. But this patch at least avoids the bugs.

**Comment by seb86** [comment]
@strangerstudios Looks all good to me. Did you add yourself to be credited on WordPress.org?

**Comment by strangerstudios** [comment]
I did not. Can you update the readme when you push? My wordpress.org username is strangerstudios

Thanks

**Comment by seb86** [comment]
Will do.

**Comment by seb86** [comment]
@strangerstudios What is the minimum version of Paid Membership Pro required for your latest fixes?

**Pull request merged**
